export {default as Frontpage} from './frontpage/Frontpage';
export {default as Loginpage} from './loginpage/Loginpage';
export {default as Studentloginpage} from './studentloginpage/Studentloginpage';
export {default as Signup} from './signup/Signup';
export {default as Homepage} from './homepage/Homepage';
export {default as Admin} from './admin/Admin';
export {default as Products} from './products/Products';
export {default as ProductPage} from './productPage/ProductPage';
export {default as Stats} from './stats/Stats';
